


# should assign the path of file like below.
# if assign only file, then it doesn't apply.
#
# source ./bashrc
#
alias l='ls -lF'
alias grep='grep -i'
alias du='du -h'
alias df='df -h'
alias cp='cp -i'
alias rm='rm -i'
alias c=clear
alias v=vi
alias m=less
alias h=history
