


# should assign the path of file like below.
# if assign only file without path, then it doesn't apply.
#
# source ./bashrc
#
alias l='ls -lF'
alias grep='grep -i'
alias du='du -h'
alias df='df -h'
alias cp='cp -i'
alias rm='rm -i'
alias c=clear
alias v=vi
alias m=less
alias h=history
alias tailf='tail -f'
alias g='/dvr/gui.tmp -disablewdt'
alias gd='/dvr/gui.tmp -disablewdt -daemon'
alias g1='mv /dvr/gui /dvr/gui.tmp'
alias g2='mv /dvr/gui.tmp /dvr/gui'
alias tv='tail -f /var/log/message'
alias u='udhcpc -i eth0'
alias fn='date +"%m%d-%H%M.log"; echo'
alias cdtmp='cd /mnt/dev2/tmp'
