# source ./bashrc
# 경로를 지정해 주어야 정상적으로 실행됨
#
alias l='ls -lF | tee'
alias grep='grep -i'
alias du='du -h'
alias df='df -h'
alias cp='cp -i'
alias rm='rm -i'
alias c=clear
alias v=vi
alias m=less
alias h=history
